apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/betelabs/platform-engineering-idp
        revision: HEAD
        directories:
          - path: gitops/apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: workloads
      source:
        repoURL: https://github.com/betelabs/platform-engineering-idp
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
